frontend/controllers/UserController.php
<?php
namespace frontend\controllers;

use Yii;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use frontend\models\LoginDetails;
use frontend\models\ContactInformation;
use common\models\Country;
use frontend\models\UserAddress;
use frontend\models\BillingHistory;
use frontend\models\UserManagement;
use frontend\models\UserUpdateManagement;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use kartik\mpdf\Pdf;
use frontend\models\Membership;

/**
 * Site controller
 */
class UserController extends Controller
{
    public $layout = "user";
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['register', 'login', 'logout', 'index', 'stats', 'settings', 'membership', 'cancel-my-account', 'login-details', 'contact-information', 'billing-and-payments', 'billing-history', 'user-management', 'create-new-user', 'update-user', 'download-pdf', 'request-password-reset', 'reset-password'],
                'rules' => [
                    [
                        'actions' => ['login', 'register', 'request-password-reset', 'reset-password'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout', 'index', 'stats', 'settings', 'membership', 'cancel-my-account', 'login-details', 'contact-information', 'billing-and-payments', 'billing-history', 'user-management', 'create-new-user', 'update-user', 'download-pdf'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        $is_payment_made = \Yii::$app->user->identity->is_payment_made;
        if($is_payment_made == 'n'){
            return $this->goHome();
        }
        
        $this->layout = "dashboard";
        return $this->render('index');
    }
    
    public function actionCamera()
    {
        
        $this->layout = "camera";
        return $this->render('camera');
    }
    
    public function actionStats()
    {
        $is_payment_made = \Yii::$app->user->identity->is_payment_made;
        if($is_payment_made == 'n'){
            return $this->goHome();
        }
        
        $this->layout = "dashboard";
        return $this->render('stats');
    }
    
    public function actionSettings()
    {
        $is_payment_made = \Yii::$app->user->identity->is_payment_made;
        if($is_payment_made == 'n'){
            return $this->goHome();
        }
        
        return $this->render('settings');
    }
    
    public function actionMembership()
    {
        $is_payment_made = \Yii::$app->user->identity->is_payment_made;
        if($is_payment_made == 'n'){
            return $this->goHome();
        }
        
        $user_id = \Yii::$app->user->identity->id;
        $model = Membership::find()->where(['id' => $user_id])->one();
        
        if ($model->load(Yii::$app->request->post())) {
            
            if ($model->update_membership_status()) {
                
                $paypal_response = \Yii::$app->user->identity->paypal_response;
                $paypal_response = unserialize($paypal_response);
                $paypal_profile_id = $paypal_response['paypal_response']['PROFILEID'];
                $paypal_profile_status = 'Suspend';
                $paypal_profile_status_reasonse = 'Profile is Suspend by User';
                
                $post_data = Yii::$app->request->post();
                $membership_status = $post_data['Membership']['membership_status'];
                if($membership_status == 'y'){  
                    $paypal_profile_status = 'Reactivate';
                    $paypal_profile_status_reasonse = 'Profile is Active by User';
                }
                \Yii::$app->mypaypal->manageProfileStatus($paypal_profile_id, $paypal_profile_status, $paypal_profile_status_reasonse);
                
                Yii::$app->getSession()->setFlash('success', 'Your membership status has been updated.');
            }else {
                Yii::$app->getSession()->setFlash('success', 'Your membership status has been updated.');
            }
        }
        
        return $this->render('membership', [ 'model' => $model]);
    }
    
    public function actionCancelMyAccount()
    {
        $is_payment_made = \Yii::$app->user->identity->is_payment_made;
        if($is_payment_made == 'n'){
            return $this->goHome();
        }
        
        $paypal_response = \Yii::$app->user->identity->paypal_response;
        $paypal_response = unserialize($paypal_response);
        $paypal_profile_id = $paypal_response['paypal_response']['PROFILEID'];
        $paypal_profile_status = 'Cancel';
        $paypal_profile_status_reasonse = 'Account is cancel by User';
        //\Yii::$app->mypaypal->manageProfileStatus($paypal_profile_id, $paypal_profile_status, $paypal_profile_status_reasonse);
                
        $model = new LoginDetails();
        $model->cancel_my_account();
        return $this->render('cancel_my_account');
    }
    
    public function actionLoginDetails()
    {
        $is_payment_made = \Yii::$app->user->identity->is_payment_made;
        if($is_payment_made == 'n'){
            return $this->goHome();
        }
        
        $user_id = \Yii::$app->user->identity->id;
        $model = LoginDetails::find()->where(['id' => $user_id])->one();
        if ($model->load(Yii::$app->request->post())) {
            
            if ($model->update_login_information()) {
                Yii::$app->getSession()->setFlash('success', 'Your login information has been updated.');
            }
        }
        return $this->render('login_details', [ 'model' => $model ]);
    }
    
    public function actionContactInformation()
    {
        $is_payment_made = \Yii::$app->user->identity->is_payment_made;
        if($is_payment_made == 'n'){
            return $this->goHome();
        }
        
        $user_id = \Yii::$app->user->identity->id;
        $model = ContactInformation::find()->where(['id' => $user_id])->one();
        if ($model->load(Yii::$app->request->post())) {
            
            if ($model->update_contact_information()) {
                Yii::$app->getSession()->setFlash('success', 'Your contact information has been updated.');
            }
        }
        return $this->render('contact_information', [ 'model' => $model ]);
    }
    
    public function actionBillingAndPayments()
    {
        
        $is_payment_made = \Yii::$app->user->identity->is_payment_made;
        $product_access = \Yii::$app->user->identity->product_access;
        if($is_payment_made == 'n' or $product_access != 1){
            return $this->goHome();
        }
        
        $user_id = \Yii::$app->user->identity->id;
        
        $model = UserAddress::find()->where(['user_id' => $user_id])->one();
        if ($model->load(Yii::$app->request->post())) { 
            if ($model->validate()) {
                if($model->save_user_address()){
                    Yii::$app->getSession()->setFlash('success', 'Your payment information has been updated.');
                }
            }            
        }
        
        $countries = Country::find()->orderBy('country_name')->all();
        return $this->render('billing_and_payments', [ 'model' => $model, 'countries' => $countries ]);
    }
    
    public function actionBillingHistory()
    {
        $is_payment_made = \Yii::$app->user->identity->is_payment_made;
        $product_access = \Yii::$app->user->identity->product_access;
        if($is_payment_made == 'n' or $product_access == 3){
            return $this->goHome();
        }
        
        $user_id = \Yii::$app->user->identity->id;
        $main_user_id = \Yii::$app->user->identity->main_user_id;
        if($main_user_id > 0){
           $user_id = $main_user_id;
        }
        $model = BillingHistory::find()->where(['user_id' => $user_id])->orderBy('created_at', 'DESC')->all();
        return $this->render('billing_history', [ 'model' => $model ]);
    }
    
    public function actionUserManagement()
    {
        $is_payment_made = \Yii::$app->user->identity->is_payment_made;
        $product_access = \Yii::$app->user->identity->product_access;
        if($is_payment_made == 'n' or $product_access != 1){
            return $this->goHome();
        }
        
        $user_id = \Yii::$app->user->identity->id;
        $model = UserManagement::find()->where(['main_user_id' => $user_id])->orderBy('id', 'DESC')->all(); 
        return $this->render('user_management', [ 'model' => $model ]);
    }
    
    public function actionCreateNewUser(){
        
        $is_payment_made = \Yii::$app->user->identity->is_payment_made;
        $product_access = \Yii::$app->user->identity->product_access;
        if($is_payment_made == 'n' or $product_access != 1){
            return $this->goHome();
        }
        $model = new UserManagement();
        
        if ($model->load(Yii::$app->request->post())) {

frontend/views/layouts/camera.php
<!DOCTYPE html>
<html lang="en" dir="ltr" xmlns:fb="http://ogp.me/ns/fb#">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <title>Web Camera Demo</title>
        <link href="http://fonts.googleapis.com/css?family=Lato:300,400,400italic,600,700|Raleway:300,400,500,600,700|Crete+Round:400italic" rel="stylesheet" type="text/css" />
        <!--[if lt IE 9]>
        <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
    <![endif]-->
    </head>
    <body>
        <?php echo $content; ?>
    </body>
</html>

frontend/views/layouts/dashboard.php
<?php

use yii\helpers\Html;
use yii\widgets\Menu;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use frontend\widgets\Alert;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <link href="http://fonts.googleapis.com/css?family=Lato:300,400,400italic,600,700|Raleway:300,400,500,600,700|Crete+Round:400italic" rel="stylesheet" type="text/css" />
        <?php $this->head() ?>
        <!--[if lt IE 9]>
        <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
    <![endif]-->
    </head>
    <body class="stretched">
        <?php $this->beginBody() ?>

        <!-- Document Wrapper
    ============================================= -->
        <div id="wrapper" class="clearfix">


            <!-- Header
            ============================================= -->
            <header id="header" class="full-header">

                <div id="header-wrap">

                    <div class="container clearfix">

                        <div id="primary-menu-trigger"><i class="icon-reorder"></i></div>

                        <!-- Logo
                        ============================================= -->
                        <div id="logo">
                            <a href="<?php echo Yii::$app->homeUrl; ?>" class="standard-logo" data-dark-logo="/canvas/images/logo-dark.png"><img src="/canvas/images/logo.png" alt="Canvas Logo"></a>
                            <a href="<?php echo Yii::$app->homeUrl; ?>" class="retina-logo" data-dark-logo="/canvas/images/logo-dark@2x.png"><img src="/canvas/images/logo@2x.png" alt="Canvas Logo"></a>
                        </div><!-- #logo end -->

                        <!-- Primary Navigation
                        ============================================= -->
                        <nav id="primary-menu">
                            <?php
                            
                            if (Yii::$app->user->isGuest) {
                                $menuItems[] = ['label' => 'Home', 'url' => ['/site/index']];
                                $menuItems[] = ['label' => 'Register Now', 'url' => ['/user/register']];
                                $menuItems[] = ['label' => 'Login', 'url' => ['/user/login']];
                            } else {
                                $menuItems[] = ['label' => '<i class="icon-dashboard"></i> Dashboard', 'url' => ['/user']];
                                $menuItems[] = ['label' => '<i class="icon-bar-chart"></i> Stats', 'url' => ['/user/stats']];
                                $menuItems[] = ['label' => '<i class="icon-book"></i> FAQ', 'url' => ['/faq']];
                                $menuItems[] = ['label' => '<i class="icon-cog"></i> Settings', 'url' => ['/user/settings']];
                                $menuItems[] = ['label' => '<i class="icon-external-link"></i> Logout', 'url' => ['/user/logout']];
                            }
                            echo Menu::widget([
                                'options' => ['class' => 'one-page-menu'],
                                'items' => $menuItems,
                                'activeCssClass' => 'tab-current',
                                'encodeLabels' => false,
                                'linkTemplate' => '<a href="{url}"><div>{label}</div></a>',
                            ]);
                            ?>
                            
                            <?php if (Yii::$app->user->isGuest) {}else{ ?>
                            <div id="top-cart">
                                <a id="top-cart-trigger" href="#"><i class="icon-comments"></i><span>2</span></a>
                            </div>
                            <?php } ?>
                            
                        </nav><!-- #primary-menu end -->


                        <!-- Top Search
                        ============================================= -->
                        <!-- #top-search end -->

                        <!-- #primary-menu end -->

                    </div>

                </div>

            </header>

            <!-- #header end -->



            <?php echo $content; ?>


        </div><!-- #wrapper end -->

        <!-- Go To Top
        ============================================= -->
        <div id="gotoTop" class="icon-angle-up"></div>
        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>

frontend/views/layouts/login.php
<?php

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use frontend\widgets\Alert;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <link href="http://fonts.googleapis.com/css?family=Lato:300,400,400italic,600,700|Raleway:300,400,500,600,700|Crete+Round:400italic" rel="stylesheet" type="text/css" />
        <?php $this->head() ?>
        <!--[if lt IE 9]>
        <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
    <![endif]-->
    </head>
    <body class="stretched">
        <?php $this->beginBody() ?>

        <!-- Document Wrapper
    ============================================= -->
        <div id="wrapper" class="clearfix">

            <!-- Content
            ============================================= -->
            <section id="content">

                <div class="content-wrap nopadding">

                    <div class="section nopadding nomargin" style="width: 100%; height: 100%; position: absolute; left: 0; top: 0; background: #444;"></div>
                    <div class="section nobg full-screen nopadding nomargin">
                        <div class="container vertical-middle divcenter clearfix">

                            <div class="row center">
                                <a href="<?php echo Yii::$app->homeUrl; ?>"><img src="/canvas/images/logo-dark.png" alt="Canvas Logo"></a>
                            </div>

                            <div class="panel panel-default divcenter noradius noborder" style="max-width: 400px;">
                                <?php echo $content; ?>
                            </div>

                            <div class="row center dark"><small>Copyright &copy; <?php echo date('Y'); ?> All Rights Reserved by Vision Solutions Ltd.</small></div>

                        </div>
                    </div>

                </div>

            </section><!-- #content end -->

        </div><!-- #wrapper end -->

        <!-- Go To Top
        ============================================= -->
        <div id="gotoTop" class="icon-angle-up"></div>
        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>

frontend/views/layouts/user.php
<?php

use yii\helpers\Html;
use yii\widgets\Menu;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use frontend\widgets\Alert;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <link href="http://fonts.googleapis.com/css?family=Lato:300,400,400italic,600,700|Raleway:300,400,500,600,700|Crete+Round:400italic" rel="stylesheet" type="text/css" />
        <?php $this->head() ?>
        <!--[if lt IE 9]>
    	<script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
    <![endif]-->
    </head>
    <body class="stretched">
        <?php $this->beginBody() ?>

        <!-- Document Wrapper
    ============================================= -->
        <div id="wrapper" class="clearfix">


            <!-- Header
            ============================================= -->
            <header id="header" class="full-header">

                <div id="header-wrap">

                    <div class="container clearfix">

                        <div id="primary-menu-trigger"><i class="icon-reorder"></i></div>

                        <!-- Logo
                        ============================================= -->
                        <div id="logo">
                            <a href="<?php echo Yii::$app->homeUrl; ?>" class="standard-logo" data-dark-logo="/canvas/images/logo-dark.png"><img src="/canvas/images/logo.png" alt="Canvas Logo"></a>
                            <a href="<?php echo Yii::$app->homeUrl; ?>" class="retina-logo" data-dark-logo="/canvas/images/logo-dark@2x.png"><img src="/canvas/images/logo@2x.png" alt="Canvas Logo"></a>
                        </div><!-- #logo end -->

                        <!-- Primary Navigation
                        ============================================= -->
                        <nav id="primary-menu">
                            
                            <?php
                            $menuItems = array();
                            if (Yii::$app->user->isGuest) {
                                $menuItems[] = ['label' => 'Home', 'url' => ['/site/index']];
                                $menuItems[] = ['label' => 'Register Now', 'url' => ['/user/register']];
                                $menuItems[] = ['label' => 'Login', 'url' => ['/user/login']];
                            }else{
                                $is_payment_made = \Yii::$app->user->identity->is_payment_made;
                                if($is_payment_made == 'y'){
                                    $menuItems[] = ['label' => '<i class="icon-dashboard"></i> Dashboard', 'url' => ['/user']];
                                    $menuItems[] = ['label' => '<i class="icon-bar-chart"></i> Stats', 'url' => ['/user/stats']];
                                    $menuItems[] = ['label' => '<i class="icon-book"></i> FAQ', 'url' => ['/faq']];
                                    $menuItems[] = ['label' => '<i class="icon-cog"></i> Settings', 'url' => ['/user/settings']];
                                    $menuItems[] = ['label' => '<i class="icon-external-link"></i> Logout', 'url' => ['/user/logout']];
                                }
                            }
                            
                            echo Menu::widget([
                                'options' => ['class' => 'one-page-menu'],
                                'items' => $menuItems,
                                'activeCssClass' => 'tab-current',
                                'encodeLabels' => false,
                                'linkTemplate' => '<a href="{url}"><div>{label}</div></a>',
                            ]);
                            ?>
                            <?php if (Yii::$app->user->isGuest) {}else{ ?>
                            <div id="top-cart">
                                <a id="top-cart-trigger" href="#"><i class="icon-comments"></i><span>2</span></a>
                            </div>
                            <?php } ?> 
                        </nav><!-- #primary-menu end -->


                        <!-- Top Search
                        ============================================= -->
                        <!-- #top-search end -->

                        <!-- #primary-menu end -->

                    </div>

                </div>

            </header>
            
            <!-- #header end -->
            
            <!-- Page Title
            ============================================= -->
            <section id="page-title">

                <div class="container clearfix">
                    <h1><?php echo Html::encode($this->title); ?></h1>
                    <?php if(isset($this->params['heading_tagline'])) { ?>
                    <span><?php echo $this->params['heading_tagline']; ?></span>
                    <?php } ?>
                    <?php
                    echo Breadcrumbs::widget([
                            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                        ]);
                    ?>
                    
                </div>

            </section>
            <!-- #page-title end -->
            
            <?php echo $content; ?>

            <footer>
            <!-- Copyrights
            ============================================= -->
            <div id="copyrights">

                <div class="container clearfix">

                    <div class="col_half">
                        Copyrights &copy; <?php echo date('Y'); ?> All Rights Reserved by Vision Solutions Ltd.<br>

                    </div>

                    <div class="col_half col_last tright">
                        <div class="fright clearfix">

                        </div>

                        <div class="clear"></div>


                    </div>

                </div>

            </div><!-- #copyrights end -->

        </footer><!-- #footer end -->

    </div><!-- #wrapper end -->

    <!-- Go To Top
    ============================================= -->
    <div id="gotoTop" class="icon-angle-up"></div>
    <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>