common/models/User.php
<?php
namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 10;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user}}';
    }
    
    
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
        ];
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return boolean
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        $parts = explode('_', $token);
        $timestamp = (int) end($parts);
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
}

frontend/controllers/UserController.php
<?php
namespace frontend\controllers;

use Yii;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use frontend\models\LoginDetails;
use frontend\models\ContactInformation;
use common\models\Country;
use frontend\models\UserAddress;
use frontend\models\BillingHistory;
use frontend\models\UserManagement;
use frontend\models\UserUpdateManagement;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use kartik\mpdf\Pdf;
use frontend\models\Membership;

/**
 * Site controller
 */
class UserController extends Controller
{
    public $layout = "user";
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['register', 'login', 'logout', 'index', 'stats', 'settings', 'membership', 'cancel-my-account', 'login-details', 'contact-information', 'billing-and-payments', 'billing-history', 'user-management', 'create-new-user', 'update-user', 'download-pdf', 'request-password-reset', 'reset-password'],
                'rules' => [
                    [
                        'actions' => ['login', 'register', 'request-password-reset', 'reset-password'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout', 'index', 'stats', 'settings', 'membership', 'cancel-my-account', 'login-details', 'contact-information', 'billing-and-payments', 'billing-history', 'user-management', 'create-new-user', 'update-user', 'download-pdf'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        $is_payment_made = \Yii::$app->user->identity->is_payment_made;
        if($is_payment_made == 'n'){
            return $this->goHome();
        }
        
        $this->layout = "dashboard";
        return $this->render('index');
    }
    
    public function actionCamera()
    {
        
        $this->layout = "camera";
        return $this->render('camera');
    }
    
    public function actionStats()
    {
        $is_payment_made = \Yii::$app->user->identity->is_payment_made;
        if($is_payment_made == 'n'){
            return $this->goHome();
        }
        
        $this->layout = "dashboard";
        return $this->render('stats');
    }
    
    public function actionSettings()
    {
        $is_payment_made = \Yii::$app->user->identity->is_payment_made;
        if($is_payment_made == 'n'){
            return $this->goHome();
        }
        
        return $this->render('settings');
    }
    
    public function actionMembership()
    {
        $is_payment_made = \Yii::$app->user->identity->is_payment_made;
        if($is_payment_made == 'n'){
            return $this->goHome();
        }
        
        $user_id = \Yii::$app->user->identity->id;
        $model = Membership::find()->where(['id' => $user_id])->one();
        
        if ($model->load(Yii::$app->request->post())) {
            
            if ($model->update_membership_status()) {
                
                $paypal_response = \Yii::$app->user->identity->paypal_response;
                $paypal_response = unserialize($paypal_response);
                $paypal_profile_id = $paypal_response['paypal_response']['PROFILEID'];
                $paypal_profile_status = 'Suspend';
                $paypal_profile_status_reasonse = 'Profile is Suspend by User';
                
                $post_data = Yii::$app->request->post();
                $membership_status = $post_data['Membership']['membership_status'];
                if($membership_status == 'y'){  
                    $paypal_profile_status = 'Reactivate';
                    $paypal_profile_status_reasonse = 'Profile is Active by User';
                }
                \Yii::$app->mypaypal->manageProfileStatus($paypal_profile_id, $paypal_profile_status, $paypal_profile_status_reasonse);
                
                Yii::$app->getSession()->setFlash('success', 'Your membership status has been updated.');
            }else {
                Yii::$app->getSession()->setFlash('success', 'Your membership status has been updated.');
            }
        }
        
        return $this->render('membership', [ 'model' => $model]);
    }
    
    public function actionCancelMyAccount()
    {
        $is_payment_made = \Yii::$app->user->identity->is_payment_made;
        if($is_payment_made == 'n'){
            return $this->goHome();
        }
        
        $paypal_response = \Yii::$app->user->identity->paypal_response;
        $paypal_response = unserialize($paypal_response);
        $paypal_profile_id = $paypal_response['paypal_response']['PROFILEID'];
        $paypal_profile_status = 'Cancel';
        $paypal_profile_status_reasonse = 'Account is cancel by User';
        //\Yii::$app->mypaypal->manageProfileStatus($paypal_profile_id, $paypal_profile_status, $paypal_profile_status_reasonse);
                
        $model = new LoginDetails();
        $model->cancel_my_account();
        return $this->render('cancel_my_account');
    }
    
    public function actionLoginDetails()
    {
        $is_payment_made = \Yii::$app->user->identity->is_payment_made;
        if($is_payment_made == 'n'){
            return $this->goHome();
        }
        
        $user_id = \Yii::$app->user->identity->id;
        $model = LoginDetails::find()->where(['id' => $user_id])->one();
        if ($model->load(Yii::$app->request->post())) {
            
            if ($model->update_login_information()) {
                Yii::$app->getSession()->setFlash('success', 'Your login information has been updated.');
            }
        }
        return $this->render('login_details', [ 'model' => $model ]);
    }
    
    public function actionContactInformation()
    {
        $is_payment_made = \Yii::$app->user->identity->is_payment_made;
        if($is_payment_made == 'n'){
            return $this->goHome();
        }
        
        $user_id = \Yii::$app->user->identity->id;
        $model = ContactInformation::find()->where(['id' => $user_id])->one();
        if ($model->load(Yii::$app->request->post())) {
            
            if ($model->update_contact_information()) {
                Yii::$app->getSession()->setFlash('success', 'Your contact information has been updated.');
            }
        }
        return $this->render('contact_information', [ 'model' => $model ]);
    }
    
    public function actionBillingAndPayments()
    {
        
        $is_payment_made = \Yii::$app->user->identity->is_payment_made;
        $product_access = \Yii::$app->user->identity->product_access;
        if($is_payment_made == 'n' or $product_access != 1){
            return $this->goHome();
        }
        
        $user_id = \Yii::$app->user->identity->id;
        
        $model = UserAddress::find()->where(['user_id' => $user_id])->one();
        if ($model->load(Yii::$app->request->post())) { 
            if ($model->validate()) {
                if($model->save_user_address()){
                    Yii::$app->getSession()->setFlash('success', 'Your payment information has been updated.');
                }
            }            
        }
        
        $countries = Country::find()->orderBy('country_name')->all();
        return $this->render('billing_and_payments', [ 'model' => $model, 'countries' => $countries ]);
    }
    
    public function actionBillingHistory()
    {
        $is_payment_made = \Yii::$app->user->identity->is_payment_made;
        $product_access = \Yii::$app->user->identity->product_access;
        if($is_payment_made == 'n' or $product_access == 3){
            return $this->goHome();
        }
        
        $user_id = \Yii::$app->user->identity->id;
        $main_user_id = \Yii::$app->user->identity->main_user_id;
        if($main_user_id > 0){
           $user_id = $main_user_id;
        }
        $model = BillingHistory::find()->where(['user_id' => $user_id])->orderBy('created_at', 'DESC')->all();
        return $this->render('billing_history', [ 'model' => $model ]);
    }
    
    public function actionUserManagement()
    {
        $is_payment_made = \Yii::$app->user->identity->is_payment_made;
        $product_access = \Yii::$app->user->identity->product_access;
        if($is_payment_made == 'n' or $product_access != 1){
            return $this->goHome();
        }
        
        $user_id = \Yii::$app->user->identity->id;
        $model = UserManagement::find()->where(['main_user_id' => $user_id])->orderBy('id', 'DESC')->all(); 
        return $this->render('user_management', [ 'model' => $model ]);
    }
    
    public function actionCreateNewUser(){
        
        $is_payment_made = \Yii::$app->user->identity->is_payment_made;
        $product_access = \Yii::$app->user->identity->product_access;
        if($is_payment_made == 'n' or $product_access != 1){
            return $this->goHome();
        }
        $model = new UserManagement();
        
        if ($model->load(Yii::$app->request->post())) {

frontend/views/user/billing_and_payments.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use yii\widgets\Menu;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

$this->title = 'Account Settings';
$this->params['breadcrumbs'][] = $this->title;

$countries_list = array();
foreach ($countries as $country){
   $countries_list[$country->country_abbrev] = $country->country_name;
}

?>

<!-- Content
============================================= -->

<section id="content">

    <div class="content-wrap">

        <div class="container clearfix">

            <div class="col_one_third nobottommargin">


                <h3>Overview</h3>
                <?php
                $product_access = \Yii::$app->user->identity->product_access;
                $menuItems = array();
                $menuItems[] = ['label' => '<i class="icon-bullseye"></i> Membership', 'url' => ['/user/membership']];
                $menuItems[] = ['label' => '<i class="icon-unlock-alt"></i> Login Details', 'url' => ['/user/login-details']];
                $menuItems[] = ['label' => '<i class="icon-envelope"></i> Contact Information', 'url' => ['/user/contact-information']];
                if($product_access == 1){
                    $menuItems[] = ['label' => '<i class="icon-user"></i> User Management', 'url' => ['/user/user-management']];
                    $menuItems[] = ['label' => '<i class="icon-dollar"></i> Billing & Payments', 'url' => ['/user/billing-and-payments']];
                }
                if($product_access == 1 or $product_access == 2){
                    $menuItems[] = ['label' => '<i class="icon-comment"></i> Billing History', 'url' => ['/user/billing-history']];
                }
                echo Menu::widget([
                    'options' => ['class' => 'sidenav'],
                    'items' => $menuItems,
                    'activeCssClass' => 'ui-tabs-active',
                    'encodeLabels' => false,
                    'linkTemplate' => '<a href="{url}"><i></i>{label}<i class="icon-chevron-right"></i></a>',
                ]);
                ?>




            </div>

            <div class="col_two_third col_last nobottommargin">                    
                <div class="col_three_third col_first nobottommargin">
                    <h3>Payment Information</h3>
                    <?php
                    $success_message = Yii::$app->session->getFlash('success');
                    if ($success_message != "") {
                        ?>
                        <div class="alert alert-success" role="alert">
                            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                            <span class="sr-only">Success:</span>
                            <?php echo $success_message; ?>
                        </div>
                    <?php } ?>
                    <div class="col_full">
                        <?php
                            $is_payment_made = \Yii::$app->user->identity->is_payment_made;
                            $membership_status = \Yii::$app->user->identity->membership_status;
                            if($is_payment_made == 'y' and $membership_status == 'y'){
                        ?>
                                Credit card is active: <span class="label label-success">Yes</span>
                            <?php } else if($membership_status == 'n') { ?>   
                                Your account is : <span class="label label-danger">Suspend</span>
                            <?php }else { ?>
                                Credit card is active: <span class="label label-danger">No</span>
                            <?php } ?>
                    </div>
                    <?php $form = ActiveForm::begin(['id' => 'billing-form', 'options' => ['class' => 'nobottommargin']]); ?>
                    <div id="ptab2">
                        <div class="row clearfix">
                            <div class="col-md-6">
                                <h3>Billing Address</h3>
                                <p class="note" style="margin-bottom: 0px;">Fields with <span class="required">*</span> are required.</p>
                                <?php echo $form->field($model, 'billing_first_name')->label('First Name <span class="required">*</span>'); ?>
                                <?php echo $form->field($model, 'billing_last_name')->label('Last Name <span class="required">*</span>'); ?>
                                <?php echo $form->field($model, 'billing_company_name')->label('Company Name <span class="required">*</span>'); ?>
                                <?php echo $form->field($model, 'billing_vat_number')->label('VAT Number <span class="required">*</span>'); ?>
                                <?php echo $form->field($model, 'billing_address')->label('Address <span class="required">*</span>'); ?>
                                <?php echo $form->field($model, 'billing_city')->label('City <span class="required">*</span>'); ?>
                                <?php echo $form->field($model, 'billing_country')->label('Country <span class="required">*</span>')->dropDownList($countries_list, ['prompt'=>'Select Country'] ); ?>
                                <?php echo Html::activeHiddenInput($model, 'billing_email_address'); ?>
                                <?php echo Html::activeHiddenInput($model, 'billing_phone'); ?>
                            </div>
                            <div class="col-md-6">
                                <h3 class="">Shipping Address</h3>
                                <p class="note" style="margin-bottom: 0px;">Fields with <span class="required">*</span> are required.</p>
                                <?php echo $form->field($model, 'shipping_first_name')->label('First Name <span class="required">*</span>'); ?>
                                <?php echo $form->field($model, 'shipping_last_name')->label('Last Name <span class="required">*</span>'); ?>
                                <?php echo $form->field($model, 'shipping_company_name')->label('Company Name <span class="required">*</span>'); ?>
                                <?php echo $form->field($model, 'shipping_vat_number')->label('VAT Number <span class="required">*</span>'); ?>
                                <?php echo $form->field($model, 'shipping_address')->label('Address <span class="required">*</span>'); ?>
                                <?php echo $form->field($model, 'shipping_city')->label('City <span class="required">*</span>'); ?>
                                <?php echo $form->field($model, 'shipping_country')->label('Country <span class="required">*</span>')->dropDownList($countries_list, ['prompt'=>'Select Country'] ); ?>    
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12" style="text-align: center;"><input type="checkbox" name="billing_same_shipping" id="billing_same_shipping" value="y" onclick="billing_same_shipping_fun();" > Shipping Address is same as Billing Address.</div>
                    <?php echo Html::submitButton('Save & Update', ['class' => 'button button-3d button-black nomargin', 'id' => 'billing-form-submit', 'name' => 'billing-form-submit', 'value' => 'Save & Update']); ?>
                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    function billing_same_shipping_fun(){
        if($('#billing_same_shipping').prop('checked')) {    
            $('#useraddress-shipping_first_name').val($('#useraddress-billing_first_name').val());
            $('#useraddress-shipping_last_name').val($('#useraddress-billing_last_name').val());
            $('#useraddress-shipping_company_name').val($('#useraddress-billing_company_name').val());
            $('#useraddress-shipping_vat_number').val($('#useraddress-billing_vat_number').val());
            $('#useraddress-shipping_address').val($('#useraddress-billing_address').val());
            $('#useraddress-shipping_city').val($('#useraddress-billing_city').val());
            $('#useraddress-shipping_country').val($('#useraddress-billing_country').val());
        }
    }
</script>
<!-- #content end -->

frontend/views/user/billing_history.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use yii\widgets\Menu;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

$this->title = 'Account Settings';
$this->params['breadcrumbs'][] = $this->title;
?>

<!-- Content
============================================= -->

<section id="content">

    <div class="content-wrap">

        <div class="container clearfix">

            <div class="col_one_third nobottommargin">


                <h3>Overview</h3>
                <?php
                $product_access = \Yii::$app->user->identity->product_access;
                $menuItems = array();
                $menuItems[] = ['label' => '<i class="icon-bullseye"></i> Membership', 'url' => ['/user/membership']];
                $menuItems[] = ['label' => '<i class="icon-unlock-alt"></i> Login Details', 'url' => ['/user/login-details']];
                $menuItems[] = ['label' => '<i class="icon-envelope"></i> Contact Information', 'url' => ['/user/contact-information']];
                if($product_access == 1){
                    $menuItems[] = ['label' => '<i class="icon-user"></i> User Management', 'url' => ['/user/user-management']];
                    $menuItems[] = ['label' => '<i class="icon-dollar"></i> Billing & Payments', 'url' => ['/user/billing-and-payments']];
                }
                if($product_access == 1 or $product_access == 2){
                    $menuItems[] = ['label' => '<i class="icon-comment"></i> Billing History', 'url' => ['/user/billing-history']];
                }
                echo Menu::widget([
                    'options' => ['class' => 'sidenav'],
                    'items' => $menuItems,
                    'activeCssClass' => 'ui-tabs-active',
                    'encodeLabels' => false,
                    'linkTemplate' => '<a href="{url}"><i></i>{label}<i class="icon-chevron-right"></i></a>',
                ]);
                ?>




            </div>

            <div class="col_two_third col_last nobottommargin">                    
                <div class="col_three_third col_first nobottommargin">
                    <h3>Billing history</h3>

                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Date</th>
                                    <th>Status</th>
                                    <th>Amount</th>
                                    <th>PDF</th>
                                    <th>Paid</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if(count($model) > 0) { $counter = 1; ?>
                                <?php foreach($model as $history) { ?>
                                <tr>
                                    <td><?php echo $counter; ?></td>
                                    <td><?php echo date('M d, y', strtotime($history->created_at)); ?></td>
                                    <td>Close</td>
                                    <td>$<?php echo $history->amount; ?></td>
                                    <td>
                                        <?php echo Html::a('Download pdf', ['user/download-pdf', 'id' => $history->id]); ?>
                                    </td>
                                    <td>Yes</td>
                                </tr>
                                <?php $counter++; } } else { ?>
                                <tr>
                                    <td colspan="4" style="text-align: center"> No Record Found </td>
                                </tr>
                                <?php } ?>
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>
<!-- #content end -->

frontend/views/user/user_management.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use yii\widgets\Menu;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

$this->title = 'Account Settings';
$this->params['breadcrumbs'][] = $this->title;
?>

<!-- Content
============================================= -->

<section id="content">

    <div class="content-wrap">

        <div class="container clearfix">

            <div class="col_one_third nobottommargin">


                <h3>Overview</h3>
                <?php
                $product_access = \Yii::$app->user->identity->product_access;
                $menuItems = array();
                $menuItems[] = ['label' => '<i class="icon-bullseye"></i> Membership', 'url' => ['/user/membership']];
                $menuItems[] = ['label' => '<i class="icon-unlock-alt"></i> Login Details', 'url' => ['/user/login-details']];
                $menuItems[] = ['label' => '<i class="icon-envelope"></i> Contact Information', 'url' => ['/user/contact-information']];
                if($product_access == 1){
                    $menuItems[] = ['label' => '<i class="icon-user"></i> User Management', 'url' => ['/user/user-management']];
                    $menuItems[] = ['label' => '<i class="icon-dollar"></i> Billing & Payments', 'url' => ['/user/billing-and-payments']];
                }
                if($product_access == 1 or $product_access == 2){
                    $menuItems[] = ['label' => '<i class="icon-comment"></i> Billing History', 'url' => ['/user/billing-history']];
                }
                echo Menu::widget([
                    'options' => ['class' => 'sidenav'],
                    'items' => $menuItems,
                    'activeCssClass' => 'ui-tabs-active',
                    'encodeLabels' => false,
                    'linkTemplate' => '<a href="{url}"><i></i>{label}<i class="icon-chevron-right"></i></a>',
                ]);
                ?>




            </div>

            <div class="col_two_third col_last nobottommargin">                    
                <div class="col_three_third col_first nobottommargin">
                    <h3>User management</h3>
                    <?php
                    $success_message = Yii::$app->session->getFlash('success');
                    if ($success_message != "") {
                        ?>
                        <div class="alert alert-success" role="alert">
                            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                            <span class="sr-only">Success:</span>
                            <?php echo $success_message; ?>
                        </div>
                    <?php } ?>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Sr. #</th>
                                    <th>Full Name</th>
                                    <th>Username</th>
                                    <th>Contact Type</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if(count($model) > 0) { $counter = 1; ?>
                                <?php foreach($model as $user) { ?>
                                <tr>
                                    <td><?php echo $counter; ?></td>
                                    <td><?php echo Html::a($user->name, ['user/update-user', 'id' => $user->id]); ?></td>
                                    <td><?php echo $user->username; ?></td>
                                    <td><?php echo $user->contact_type; ?></td>
                                </tr>
                                <?php $counter++; } } else{ ?>
                                <tr>
                                    <td colspan="4" style="text-align: center"> No Record Found </td>
                                </tr>
                                <?php } ?>
                            </tbody>
                        </table>
                        <?php echo Html::a('Create new user', ['user/create-new-user'], ['class' => 'button button-3d button-black nomargin']); ?>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>
<!-- #content end -->